### ISSUE TITLE
WebAssembly-specific bindings

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/cg-charter#2]
I don't think the charter should mention adding "WebAssembly-specific  bindings" for an ad hoc subset of Web APIs (currently, IDB, WebGL, WebGPU).  This makes it sound like each Web API will need a bespoke WebAssembly binding which I think we should categorically avoid (preferring instead to bind WebAssembly generically to WebIDL).  Since we should actually work with the listed groups to ensure that their APIs integrate well (in terms of performance, ergonomics) with WebAssembly, could we just generalize the descriptions a bit?

Related, I don't know what "direct write access" means, but it vaguely sounds like giving WebAssembly some special privilege or API which I don't think we should do or have in the charter.

**Comment by flagxor** [comment]
Good point.
I'd been encouraged to be very specific the charters at one point, but prescribing a solution is too much in a charter. Reworded.
I tend to agree we'll want to reuse WebIDL bindings, though I suspect we may need to tweak some APIs to make that performant + ergonomic.
Yes agreed on the write access thing, that's not even a fully formed thought. :-)
Please check out the change I made and close this if it addresses the issue.

**Comment by lukewagner** [comment]
Thanks!
